=== cp-weiland/openDS-schema/schema-4.json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "$id": "https://nsidr.org/schemas/opendsschema.json",
    "description": "v0.4, 22 February 2021. JSON schema for an open Digital Specimen.",
    "type": "object",
    "title": "ODStype1802",
    "properties": {
        "id": {
            "type": "string"
        },
        "typeName": {
            "type": "string",
            "const": "ODStype1802"
        },
        "authoritative": {
            "$id": "#/properties/a_section",
            "type": "object",
            "properties": {
                "modified": {
                    "type": "string",
                    "title": "Modified (date:time)",
                    "format": "date-time"
                },
                "midsLevel": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 3
                },
                "physicalSpecimenId": {
                    "type": "string",
                    "title": "Physical specimen identifier"
                },
                "institution": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string",
                            "title": "Code (GRSciColl)"
                        },
                        {
                            "type": "string",
                            "format": "uri",
                            "title": "Referent"
                        }
                    ]
                },
                "materialType": {
                    "type": "string",
                    "title": "Material type"
                },
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "title": "Name"
                }
            },
            "required": [
                "modified",
                "midsLevel",
                "physicalSpecimenId",
                "institution",
                "materialType",
                "name"
            ]
        },
        "images": {
            "$id": "#/properties/i_section",
            "type": "object",
	    "required": [],
	    "properties": {
		"img" : {
		    "type": "array",
		    "items": { "$ref": "#/$defs/image" }
		}
	    }
	},
        "supplementary": {
            "$id": "#/properties/s_section",
            "type": "object",
            "properties": {
            },
            "required": []
        },
        "tertiary": {
            "$id": "#/properties/t_section",
            "type": "object",
            "properties": {
            },
            "required": []
        }
    },
    "required": [
        "id",
        "typeName",
        "authoritative"
    ],

    "$defs": {
	"image" : {
	    "type": "object",
	    "required": [ "src" ],
	    "properties": {
		"format": {
		    "type": "string"
		},
		"src": {
		    "type" : "string"
		}
	    }
	}
    }
}

=== cp-weiland/openDS-schema/example-SeSam-452904.json
{
    "id": "20.5000.1025/SeSam-452904",
    "typeName": "ODStype1802",
    "authoritative": {
        "modified": "2021-05-02T14:16:25.136954",
        "midsLevel": 1,
        "physicalSpecimenId": "https://id.senckenberg.de/object/SeSam-452904",
        "institution": [
            "FR",
            "https://ror.org/00xmqmx64"
        ],
        "materialType": "Alcohol",
        "name": "Deroceras reticulatum (O. F. MÃ¼ller, 1774)"
    },
    "images": {
	"img":[
	    {
		"src": "https://search.senckenberg.de/viewer/?id=sesam-96-19033.jpg",
		"format": "image/jpeg"
	    },
	    {
		"src": "https://search.senckenberg.de/viewer/?id=sesam-96-19032.jpg",
		"format": "image/jpeg"
	    }
	]
    }
}
